var express=require('express');
var expressLayouts = require('express-ejs-layouts');
var session=require('express-session');
var favicon=require('serve-favicon');
var app=express();
var trackController=require('./controllers/trackController');
var loginController=require('./controllers/loginController');
var bodyParser=require('body-parser');
app.set('view engine','ejs');
app.use(expressLayouts);
app.use(express.static('./public'));
app.use(express.json());
app.use(bodyParser.json());
app.use(bodyParser.urlencoded({extended:true}));
trackController(app);
loginController(app);
const passport = require('passport');
app.use(passport.initialize());
app.use(passport.session());
app.listen(4000);
console.log('server listening');